identidock:
  build: .
  ports:
    # - "80:9090"
    - "80:5000"
  environment:
    RUN: DEV
  volumes:
    - ./app:/app
  links:
    - dnmonster
    - redis

dnmonster:
  image: amouat/dnmonster

redis:
  image: redis