proxy:
  image: avis20/proxy:0.1
  environment:
    - NGINX_HOST=3.3.3.3
    - NGINX_PROXY=http://identidock:9090
  links:
    - identidock
  ports:
    - "80:80"

identidock:
  image: avis20/identidock:1.0
  environment:
    RUN: PROD
  links:
    - dnmonster
    - redis

dnmonster:
  image: amouat/dnmonster

redis:
  image: redis

logspout:
  image: avis20/logspout-logstash:1.0
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "8000:80"
  links:
    - logstash
  command: logstash://logstash:5000

logstash:
  image: logstash:5-alpine
  volumes:
    - ./logstash.conf:/etc/logstash.conf
  environment:
    LOGSPOUT: ignore
  links:
    - elasticsearch
  command: -f /etc/logstash.conf

elasticsearch:
  image: elasticsearch:5.6.15-alpine
  environment:
    LOGSPOUT: ignore

kibana:
  image: kibana:5.6.16
  environment:
    LOGSPOUT: ignore
    ELASTICSEARCH_URL: http://elasticsearch:9200
  links:
    - elasticsearch
  ports:
    - "5601:5601"

