Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.host_name = "vagrant.vm"
  config.vm.network "private_network", ip: "192.168.33.10", auto_config: false
  config.vm.provision 'shell', inline: "ifconfig eth1 192.168.33.10"
end