identidock:
  build: .
  ports:
    - "80:9090"
    - "81:5000"
  environment:
    RUN: DEV
  volumes:
    - ./app:/app
  links:
    - dnmonster

dnmonster:
  image: amouat/dnmonster


# $ docker run --rm -p 80:5000 -e "RUN=DEV" -v "$(pwd)"/app:/app --name identidock --link dnmonster:dnmonster identidock 