Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "private_network", ip: "33.33.33.10", auto_config: false
  config.vm.provision 'shell', inline: "ifconfig eth1 33.33.33.10"
end